name: Deploy to STRATO via SFTP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload to ftp
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_PASS: ${{ secrets.SFTP_PASS }}
          SFTP_REMOTE_PATH: ${{ secrets.SFTP_REMOTE_PATH }}
        run: |
          sftp -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -P "$SFTP_PORT" "$SFTP_USER@$SFTP_HOST" <<EOF
put -r * "$SFTP_REMOTE_PATH"
EOF